### PR TITLE
Issue #32: Fix scaling issue for large classes with high concurrent users

### PR DESCRIPTION
**Pull request by pauldamiani**

### CODE REVIEW

**Comment by brendanheywood** [comment]
@deraadt any chance you could review this please? See #32 

This patch is quite simple but has quite big impact on performance, eg 4 seconds of processing on a large page:

image

**Comment by agrowe** [comment]
There was a new release recently but this was not included. Was there a reason for skipping this simple change as it causes issues on sites with lots of users?

**Comment by brendanheywood** [comment]
We'd seen clients with ~10 instances of this block on one course page and the performance is horrendous without this patch, ie 30+ seconds

I still think there can be even more work done to reuse some lookups when there are multiple block instances on the same page but we'll sort another pr for that

**Comment by agrowe** [comment]
Looking at our Percona Monitoring and Management application, this morning this single query is 0.11% of all total queries but is causing 5.21% of our database load.

Having 1000 users logging in and accessing a course with this block enabled, at the same time, is putting unnecessary load on our DB server.

**Comment by DegrangeM** [comment]
@jonof Is tagged as "Lead maintainer" on the moodle plugin page, so maybe he can check this.

**Comment by brendanheywood** [comment]
The repos links are wrong in the plugin dir, I've logged https://github.com/deraadt/moodle-block_completion_progress/issues/61 to sort that out

**Comment by jonof** [comment]
Seems it's difficult to get a reproduction using a synthetically generated medium-size course and several hundred exclusions to be quite as bad as the profile shot above suggests, but I'll believe you. A formal release will come soon.

**Comment by brendanheywood** [comment]
thanks heaps @jonof

**Pull request merged**
